### PR TITLE
bind to 127.0.0.1 by default

### PR DESCRIPTION
**Pull request by MichaelSp**
This is a fix for https://github.com/kstyrc/embedded-redis/issues/45

### CODE REVIEW

**Comment by MichaelSp** [comment]
Thanks @robertotru 
when can I expect the next release on mvn central?

**Comment by robertotru** [comment]
Well, tests are now red! I'd like to release asap, but first tests must pass.

**Comment by MichaelSp** [comment]
This is the reason it is not working: https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/HostAndPort.java#L145

**Comment by robertotru** [comment]
I see. Do you think that you can quickly fix the build? Otherwise, I will try to spend some free time in the next days.

**Comment by MichaelSp** [comment]
Reason: `127.0.0.1` and `localhost` will be converted to the public address to satisfy https://github.com/xetorthio/jedis/issues/1424 . Binding to `127.0.0.1` now results in the server being not reachable.
I was able to solve it by downgrading to `redis.clients:jedis:2.8.2` - is that an option for you?

**Comment by robertotru** [comment]
Sure! Please, let's go with the pull request

**Comment by robertotru** [comment]
@MichaelSp release 0.7.2 has been done, it is in staging at the moment. It will be available in Maven Central probably within this evening.

**Comment by MichaelSp** [comment]
perfect! Thanks a lot  🎉

**Comment by robertotru** [comment]
Thanks you for the valuable contribution

**Comment by shalk** [comment]
i found some bug here .  when i use   `configFile`, `new RedisBuildingException("Redis configuration is already partially build using setting(String) method!");` will be throw.

```
      RedisServer.builder()
           .configFile(new File("src/test/resources/master.conf").getAbsolutePath())
         .build();
```

may be should fix it here.
```
  public RedisServer build() {
        setting("bind "+bind);
        tryResolveConfAndExec();
        List<String> args = buildCommandArgs();
```

**Pull request merged**
